# Generated by Django 5.2.2 on 2026-02-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_book_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="date_of_birth",
            new_name="birth",
        ),
    ]
