# Generated by Django 5.2.2 on 2026-02-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
    ]
